drop database if exists escola;
create database	escola;
use escola;
create table alunos(
id int NOT NULL AUTO_INCREMENT,
    nome varchar(30),
    grupo enum('a', 'b', 'c', 'd'),
    nascimento DATE,
    clube varchar(10),
    cor_favorita varchar(10),
    profissao varchar (20),
    nacionalidade varchar (20) default 'brasileira',
    habilitado enum ('sim', 'não'),    
    sexo enum ('F', 'M'),
    filme varchar (10), 
    PRIMARY KEY (id)
    )    DEFAULT CHARSET = utf8; 
    
    insert into alunos values
	(default, "ADRIANO YUDI TAKARA", "a", "21-01-2003", "alpha", "azul", "Mecânico", default, "sim", "M", "Milagre"),
	(default, "ALISSIA COELHO OLIVEIRA", "b", "22-02-2002", "beta", "rosa", "Motorista", "chinesa", "sim", "F", "Bola"),
	(default, "ANDRE LUIS FIALHO DE OLIVEIRA MIRANDA", "c", "23-03-2001", "delta", "verde", "Manobrista", "italiana", "sim", "M", "Fenix"),
	(default, "ANTONIO GARCIA MARQUES DE OLIVEIRA", "d", "24-04-2000", "pi", "vermelho", "Guitarrista", "portuguesa", "sim", "M", "Pegasos"),
	(default, "ARTHUR DA SILVA", "a", "25-05-1999", "alpha", "azul", "jogador_futebol", "colombiana", "não", "M", "Barco"),
	(default, "CAIO DANIEL BEZERRA PINHEIRO", "b", "26-06-1998", "beta", "rosa", "Jogador_Golge", "americana", "não", "M", "Abelhas"),
	(default, "CARLOS EDUARDO MARIANO DOS SANTOS", "c", "27-07-1997", "delta", "verde", "Cosplay", "japonesa", "sim", "M", "Tubarão"),
	(default, "ERICK GUSTAVO CHOQUE QUISPE", "d", "28-08-1996", "pi", "vermelho", "Guarda_costa", default, "sim", "M", "Milagre"),
	(default, "FRANCISCO MIGUEL FERREIRA DE MOURA", "a", "29-09-1995", "alpha", "azul", "Mecânico", "chinesa", "sim", "M", "Bola"),
	(default, "GABRIEL ACEVEDO", "b", "30-10-1994", "beta", "rosa", "Motorista", "italiana", "sim", "M", "Fenix"),
	(default, "GABRIEL CAMARA DA SILVA", "c", "21-11-1993", "delta", "verde", "Manobrista", "portuguesa", "não", "M", "Pegasos"),
	(default, "GABRIELLE URBANO AZEVEDO", "d", "22-12-1992", "pi", "vermelho", "Guitarrista", "colombiana", "não", "F", "Barco"),
	(default, "HEITOR LEAL DE SOUZA MARQUES DA SILVA", "a", "23-01-1992", "alpha", "azul", "jogador_futebol", "americana", "sim", "M", "Abelhas"),
	(default, "HENRIQUE NICHII LOPES", "b", "24-02-1991", "beta", "rosa", "Jogador_Golge", "japonesa", "sim", "M", "Tubarão"),
	(default, "ITALO BUKYS", "c", "25-03-1990", "delta", "verde", "Cosplay", default, "sim", "M", "Milagre"),
	(default, "JEAN MARCEL MARTINS FILHO", "d", "26-04-1989", "pi", "vermelho", "Guarda_costa", "chinesa", "sim", "M", "Bola"),
	(default, "JHONATHAN DOS SANTOS DOURADO", "a", "27-05-1988", "alpha", "azul", "Mecânico", "italiana", "não", "M", "Fenix"),
	(default, "JOAO PEDRO MONTEIRO SOUTO", "b", "28-06-1987", "beta", "rosa", "Motorista", "portuguesa", "não", "M", "Pegasos"),
	(default, "JOÃO VITOR DE SOUSA SILVA", "c", "29-07-1986", "delta", "verde", "Manobrista", "colombiana", "sim", "M", "Barco"),
	(default, "JUAN DOS SANTOS HERNANDES", "d", "30-08-1985", "pi", "vermelho", "Guitarrista", "americana", "sim", "M", "Abelhas"),
	(default, "KAUA GOMES DOS SANTOS", "a", "21-09-1984", "alpha", "azul", "jogador_futebol", "japonesa", "sim", "M", "Tubarão"),
	(default, "KAUAN HIKARU MURATA YOGI", "b", "22-10-1983", "beta", "rosa", "Jogador_Golge", default, "sim", "M", "Milagre"),
	(default, "LUCAS GOMES ANTUNES", "c", "23-11-1982", "delta", "verde", "Cosplay", "chinesa", "não", "M", "Bola"),
	(default, "LUCAS LIRA MONTEIRO SOARES", "d", "24-12-1981", "pi", "vermelho", "Guarda_costa", "italiana", "não", "M", "Fenix"),
	(default, "LUCAS SOUSA SILVA", "a", "25-01-1981", "alpha", "azul", "Mecânico", "portuguesa", "sim", "M", "Pegasos"),
	(default, "LUCAS VECHI LIGGI", "b", "26-02-1980", "beta", "rosa", "Motorista", "colombiana", "sim", "M", "Barco"),
	(default, "LUIS PONTES OTA", "c", "27-03-1979", "delta", "verde", "Manobrista", "americana", "sim", "M", "Abelhas"),
	(default, "LUIZ RAIMUNDO NETO", "d", "28-04-1978", "pi", "vermelho", "Guitarrista", "japonesa", "sim", "M", "Tubarão"),
	(default, "MARIA BEATRIZ FERNANDES LOPES", "a", "29-05-1977", "alpha", "azul", "jogador_futebol", default, "não", "F", "Milagre"),
	(default, "MARIA CLARA SILVA DE MELO", "b", "30-06-1976", "beta", "rosa", "Jogador_Golge", "chinesa", "não", "F", "Bola"),
	(default, "MATEUS AUGUSTO SANTOS FERNANDES", "c", "21-07-1975", "delta", "verde", "Cosplay", "italiana", "sim", "M", "Fenix"),
	(default, "MELISSA RIE KANZATO", "d", "22-08-1974", "pi", "vermelho", "Guarda_costa", "portuguesa", "sim", "F", "Pegasos"),
	(default, "PEDRO HENRIQUE PASSOS MARTINS", "a", "23-09-1973", "alpha", "azul", "Mecânico", "colombiana", "sim", "M", "Barco"),
	(default, "RENAN ENZO MORITA", "b", "24-10-1972", "beta", "rosa", "Motorista", "americana", "sim", "M", "Abelhas"),
	(default, "RENAN FERNANDES DANTAS", "c", "25-11-1971", "delta", "verde", "Manobrista", "japonesa", "não", "M", "Tubarão"),
	(default, "RYAN REIS DOS SANTOS", "d", "26-12-1970", "pi", "vermelho", "Guitarrista", default, "não", "M", "Milagre"),
	(default, "SARAH RUFINO REIS", "a", "27-01-1970", "alpha", "azul", "jogador_futebol", "chinesa", "sim", "F", "Bola"),
	(default, "SOFIA ANSANELO MARTINS", "b", "28-02-1969", "beta", "rosa", "Jogador_Golge", "italiana", "sim", "F", "Fenix"),
	(default, "TAINÁ MARCONDES TOINAKI", "c", "29-03-1968", "delta", "verde", "Cosplay", "portuguesa", "sim", "F", "Pegasos"),
	(default, "VICENZO GADELHA GRECO", "d", "30-04-1967", "pi", "vermelho", "Guarda_costa", "colombiana", "sim", "M", "Barco");
    
    select * from alunos;